name: container-build-artifact-secrets-pages
run-name: Build in Container, Upload Artifacts, Access Secrets, Deploy to Pages
permissions:
  contents: write
on:
  push:
    branches: [ topic/init-gh-secrets ]
jobs:
  container-npm-run-build-secrets-artifacts-deploy:
    environment: staging
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        working-directory: ./app
        env:
          REACT_APP_ENV_SECRET: ${{ secrets.GH_ENV_SECRET }}
          REPO_SECRET: ${{ secrets.TEST_REPO_SECRET }}
        run: |
          apt-get update && apt-get install -y rsync
          npm ci
          npm run build

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build       # results in build.zip of directory
          path: app/build/
          retention-days: 7

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build # default is to create/update branch gh-pages
