name: secrets
run-name: Echo Secret
permissions:
  contents: write
on:
  push:
    branches: [ topic/init-gh-secrets ]
jobs:
  output-secrets:
    #
    # https://docs.github.com/en/actions/security-guides/encrypted-secrets#accessing-your-secrets
    # Organization and repository secrets are read when a workflow run is queued
    #
    # environment secrets are read when a job __referencing the environment__
    # starts.
    environment: staging # need this otherwise env secrets are empty
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1
    steps:
      - name: Env Test
        env:
          TEST_ENV: hello
          REACT_APP_ENV_SECRET: ${{ secrets.GH_ENV_SECRET }}
          REPO_SECRET: ${{ secrets.TEST_REPO_SECRET }}
        run: |
          echo "$TEST_ENV"
          echo "$REACT_APP_ENV_SECRET"
          echo "$REPO_SECRET"
          echo ${{ secrets.GH_ENV_SECRET }}
          echo "Done"
